PROGS	:= bdpandl
OBJS	:= dlinfo.o dlpart.o dlcommon.o dlscrolling.o dlbuffer.o \
	   dllist.o dlssl.o err_handler.o
CFLAGS	:= -Wall -lpthread -lcurl
CC	:= x86_64-w64-mingw32-gcc


ALL: $(PROGS) $(TOOLS)

debug: ALL
debug: CFLAGS+=-g


%.o: %.c
	$(CC) -c $^ $(CFLAGS)

bdpandl: bdpandl.c $(OBJS)
	$(CC) -o $@.exe $^ $(CFLAGS)


.PHONY: ALL debug clean install uninstall
clean:
	$(RM) $(OBJS) $(PROGS) $(TOOLS) $(wildcard *.h.gch)

install:
	cp $(PROGS) /usr/bin

uninstall:
	$(RM) /usr/bin/$(PROGS)
